### ISSUE TITLE
missing antifraud.py file

### ISSUE THREAD

**Issue by ghprud** [InsightDataScience/digital-wallet#1]
I tried compiling the code using run.sh and I get a missing antifraud.py file error. Can you please look into this?

Thanks!

**Comment by emhoa** [comment]
If you intend to code in Python, you are expected to place your main method in a a file -- which you can name antifraud.py and place in the src folder yourself. Once you do that, the run.sh script should execute as expected.

If you intend to code in another language, you can place your code in the src folder and then modify the run.sh script to compile the code (if necessary) and execute it.
